services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - OLLAMA_API=http://localhost:11434

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"